###
GET http://172.16.1.42:3000

###
POST http://localhost:3000/Alunos
Content-Type: application/json

{
    "nome":"Emerson Rocha",
    "email" : "EmersonRocha@etec.sp.gov.br" 
}

###
PUT http://localhost:3000/update/1
Content-Type: application/json

{
    "nome" : "zé pilantra",
    "email" : "zeze@etec.sp.gov.br"
}

###
DELETE http://172.16.1.42:3000/delete/1